# Generated by Django 4.0.6 on 2022-09-01 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='agree_with_agreement',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.FileField(default=None, upload_to='uploads/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_number',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('passport_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('agree_with_agreement', models.BooleanField(default=False)),
                ('passport', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('photo', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
