# Generated by Django 4.0.6 on 2022-09-13 12:33

import api.decorators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.FileField(upload_to=api.decorators.UploadTo('passport')),
        ),
    ]
