# Generated by Django 4.1.1 on 2022-09-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_university_alter_student_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='agree_with_agreement',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='price',
        ),
        migrations.RemoveField(
            model_name='student',
            name='university_cert',
        ),
    ]
