# Generated by Django 4.1.1 on 2022-09-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
