# Generated by Django 4.1.1 on 2022-09-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passport',
            field=models.FileField(default=None, upload_to='uploads/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
