# Generated by Django 4.0.6 on 2022-09-13 17:09

import api.decorators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_sponsor_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='passport',
            field=models.FileField(default=None, upload_to=api.decorators.UploadTo('passport')),
            preserve_default=False,
        ),
    ]
